# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb6e588405e58de79d7d1507ab5189087144db5707a40d39dfbd0ffede66e323b9c5b7a6a68a8aa47763133dce9d629f4395f53a3c1deb1e4f4716107ad6539e

test:
  secret_key_base: a7d74ffdf4dcd0671b4ea3cbdc115d69e6d25dc2911c4b82c7c819cd9ffc2322c7463bbf1b40f94a85d66a4be1f9685ab789fba62e16b93ecd2b8a2bb69195ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
